# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
#  boot.initrd.preDeviceCommands = ''
#    DEVS="0000:26:00.0 0000:26:00.1"
#    for DEV in $DEVS; do
#      echo "vfio-pci" > /sys/bus/pci/devices/$DEV/driver_override
#    done
#    modprobe -i vfio-pci
#  '';

  fileSystems."/" =
    { device = "/dev/disk/by-label/root";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/home";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/swapfile";
      size = (1024 * 8) + (1024 * 2);
    }
  ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
